//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllArmsView
    {
        public string ORG_NAME { get; set; }
        public string ANL_INVOICE { get; set; }
        public string AT_NAME { get; set; }
        public string ARM_NUMBER { get; set; }
        public int ARM_ID { get; set; }
        public int ORG_ID { get; set; }
        public int ANL_ID { get; set; }
        public int AT_ID { get; set; }
        public string armTypeNew { get; set; }
    }
}
