//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTENNA_CALIBRATION
    {
        public int ANT_CAL_ID { get; set; }
        public int ANT_CAL_ANT_ID { get; set; }
        public double ANT_CAL_F { get; set; }
        public double ANT_CAL_VALUE { get; set; }
        public string ANT_CAL_NOTE { get; set; }
    
        public virtual ANTENNA ANTENNA { get; set; }
    }
}
