//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARM
    {
        public ARM()
        {
            this.ANTENNA_ARM = new HashSet<ANTENNA_ARM>();
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.MEASURING_EQUIPMENT_ARM = new HashSet<MEASURING_EQUIPMENT_ARM>();
            this.MEASURING_DEVICE_ARM = new HashSet<MEASURING_DEVICE_ARM>();
            this.MODE = new HashSet<MODE>();
        }
    
        public int ARM_ID { get; set; }
        public Nullable<int> ARM_AT_ID { get; set; }
        public string ARM_NUMBER { get; set; }
        public int ARM_KATEGORIA { get; set; }
        public string ARM_SVT { get; set; }
        public string ARM_NK { get; set; }
        public string ARM_IK { get; set; }
        public string ARM_TT { get; set; }
        public string ARM_NOTE { get; set; }
        public Nullable<int> ARM_ANT_ID { get; set; }
    
        public virtual ICollection<ANTENNA_ARM> ANTENNA_ARM { get; set; }
        public virtual ARM_TYPE ARM_TYPE { get; set; }
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual ICollection<MEASURING_EQUIPMENT_ARM> MEASURING_EQUIPMENT_ARM { get; set; }
        public virtual ICollection<MEASURING_DEVICE_ARM> MEASURING_DEVICE_ARM { get; set; }
        public virtual ANTENNA ANTENNA { get; set; }
        public virtual ICollection<MODE> MODE { get; set; }
    }
}
