//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUserTask
    {
        public int CUT_ID { get; set; }
        public Nullable<int> CUT_ORG_ID { get; set; }
        public Nullable<int> CUT_ANL_ID { get; set; }
        public Nullable<int> CUT_AT_ID { get; set; }
        public Nullable<int> CUT_ARM_ID { get; set; }
        public Nullable<int> CUT_MODE_ID { get; set; }
        public string CUT_USER_NAME { get; set; }
    }
}
