//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public int EQ_ID { get; set; }
        public Nullable<int> EQ_EQT_ID { get; set; }
        public Nullable<int> EQ_ARM_ID { get; set; }
        public string EQ_MODEL { get; set; }
        public string EQ_SERIAL { get; set; }
        public Nullable<int> EQ_PROD_ID { get; set; }
        public Nullable<int> EQ_COUNTRY_ID { get; set; }
        public Nullable<int> EQ_PARENT_ID { get; set; }
        public Nullable<int> EQ_SZZ { get; set; }
        public string EQ_NOTE { get; set; }
        public Nullable<bool> EQ_IN_MODE { get; set; }
        public Nullable<double> EQ_F_DEFAULT { get; set; }
    
        public virtual ARM ARM { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual EQUIPMENT_TYPE EQUIPMENT_TYPE { get; set; }
        public EQUIPMENT DeepCopy()
        {
            EQUIPMENT other = new EQUIPMENT();
            other.EQ_COUNTRY_ID = ((EQUIPMENT)this).EQ_COUNTRY_ID;
            other.EQ_EQT_ID = ((EQUIPMENT)this).EQ_EQT_ID;
            other.EQ_MODEL = ((EQUIPMENT)this).EQ_MODEL;
            other.EQ_NOTE = ((EQUIPMENT)this).EQ_NOTE;
            other.EQ_PARENT_ID = ((EQUIPMENT)this).EQ_PARENT_ID;
            other.EQ_PROD_ID = ((EQUIPMENT)this).EQ_PROD_ID;
            other.EQ_COUNTRY_ID = ((EQUIPMENT)this).EQ_COUNTRY_ID;
            other.EQ_SERIAL = ((EQUIPMENT)this).EQ_SERIAL;
            other.EQ_SZZ = ((EQUIPMENT)this).EQ_SZZ;
            other.EQ_IN_MODE = ((EQUIPMENT)this).EQ_IN_MODE;
            other.EQ_F_DEFAULT = ((EQUIPMENT)this).EQ_F_DEFAULT;
            return other;
        }
        public virtual PRODUCER PRODUCER { get; set; }
    }
}
