//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT_TYPE
    {
        public EQUIPMENT_TYPE()
        {
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
        }
    
        public int EQT_ID { get; set; }
        public string EQT_NAME { get; set; }
        public string EQT_NOTE { get; set; }
    
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
    }
}
