//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIDER_CALIBRATION
    {
        public int F_CAL_ID { get; set; }
        public int F_CAL_F_ID { get; set; }
        public double F_CAL_F { get; set; }
        public double F_CAL_VALUE { get; set; }
        public string F_CAL_NOTE { get; set; }
    
        public virtual FIDER FIDER { get; set; }
    }
}
