//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_DEVICE_ARM
    {
        public int MDARM_ID { get; set; }
        public Nullable<int> MDARM_MD_ID { get; set; }
        public Nullable<int> MDARM_ARM_ID { get; set; }
    
        public virtual ARM ARM { get; set; }
        public virtual MEASURING_DEVICE MEASURING_DEVICE { get; set; }
    }
}
