//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_DEVICE
    {
        public MEASURING_DEVICE()
        {
            this.MEASURING_DEVICE_ARM = new HashSet<MEASURING_DEVICE_ARM>();
        }
    
        public int MD_ID { get; set; }
        public Nullable<int> MD_MDT_ID { get; set; }
        public string MD_MODEL { get; set; }
        public string MD_WORKNUMBER { get; set; }
        public string MD_F_INTERVAL { get; set; }
        public Nullable<System.DateTime> MD_DATE { get; set; }
        public double MD_ERROR { get; set; }
        public string MD_DEFAULT { get; set; }
        public string MD_OWNER { get; set; }
        public string MD_NOTE { get; set; }
        public string MD_IS_HELPER { get; set; }
    
        public virtual ICollection<MEASURING_DEVICE_ARM> MEASURING_DEVICE_ARM { get; set; }
        public virtual MEASURING_DEVICE_TYPE MEASURING_DEVICE_TYPE { get; set; }
    }
}
