//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_EQUIPMENT_TYPE
    {
        public MEASURING_EQUIPMENT_TYPE()
        {
            this.MEASURING_EQUIPMENT = new HashSet<MEASURING_EQUIPMENT>();
        }
    
        public int MET_ID { get; set; }
        public string MET_NAME { get; set; }
        public string MET_NOTE { get; set; }
    
        public virtual ICollection<MEASURING_EQUIPMENT> MEASURING_EQUIPMENT { get; set; }
    }
}
