//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_EQUIPMENT
    {
        public MEASURING_EQUIPMENT()
        {
            this.MEASURING_EQUIPMENT_ARM = new HashSet<MEASURING_EQUIPMENT_ARM>();
        }
    
        public int ME_ID { get; set; }
        public Nullable<int> ME_MET_ID { get; set; }
        public string ME_MODEL { get; set; }
        public string ME_SERIAL { get; set; }
        public string ME_INTERVAL { get; set; }
        public string ME_NOTE { get; set; }
    
        public virtual ICollection<MEASURING_EQUIPMENT_ARM> MEASURING_EQUIPMENT_ARM { get; set; }
        public virtual MEASURING_EQUIPMENT_TYPE MEASURING_EQUIPMENT_TYPE { get; set; }
    }
}
