//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_DATA
    {
        public int MDA_ID { get; set; }
        public int MDA_MODE_ID { get; set; }
        public double MDA_F { get; set; }
        public int MDA_F_UNIT_ID { get; set; }
        public int MDA_I { get; set; }
        public double MDA_ECN_VALUE_IZM { get; set; }
        public double MDA_EN_VALUE_IZM { get; set; }
        public double MDA_U0CN_VALUE_IZM { get; set; }
        public double MDA_U0N_VALUE_IZM { get; set; }
        public double MDA_UFCN_VALUE_IZM { get; set; }
        public double MDA_UFN_VALUE_IZM { get; set; }
        public double MDA_ES_VALUE_IZM { get; set; }
        public double MDA_ECN_VALUE_IZM_DB { get; set; }
        public double MDA_EN_VALUE_IZM_DB { get; set; }
        public double MDA_U0CN_VALUE_IZM_DB { get; set; }
        public double MDA_U0N_VALUE_IZM_DB { get; set; }
        public double MDA_UFCN_VALUE_IZM_DB { get; set; }
        public double MDA_UFN_VALUE_IZM_DB { get; set; }
        public double MDA_ES_VALUE_IZM_DB { get; set; }
        public double MDA_ECN_VALUE_IZM_MKV { get; set; }
        public double MDA_EN_VALUE_IZM_MKV { get; set; }
        public double MDA_U0CN_VALUE_IZM_MKV { get; set; }
        public double MDA_U0N_VALUE_IZM_MKV { get; set; }
        public double MDA_UFCN_VALUE_IZM_MKV { get; set; }
        public double MDA_UFN_VALUE_IZM_MKV { get; set; }
        public double MDA_ES_VALUE_IZM_MKV { get; set; }
        public double MDA_EGS_DB { get; set; }
        public double MDA_EGS_MKV { get; set; }
        public double MDA_E { get; set; }
        public double MDA_UF { get; set; }
        public double MDA_U0 { get; set; }
        public double MDA_EGS { get; set; }
        public double MDA_KP { get; set; }
        public double MDA_KPS { get; set; }
        public double MDA_RBW { get; set; }
        public int MDA_RBW_UNIT_ID { get; set; }
        public Nullable<int> MDA_ANT_ID { get; set; }
        public double MDA_KA { get; set; }
        public double MDA_KF { get; set; }
        public double MDA_K0 { get; set; }
        public double MDA_F_BEGIN { get; set; }
        public double MDA_F_END { get; set; }
        public double MDA_ECN_BEGIN { get; set; }
        public double MDA_EN_BEGIN { get; set; }
        public double MDA_ECN_END { get; set; }
        public double MDA_EN_END { get; set; }
        public int MDA_ANGLE { get; set; }
        public string MDA_TYPE { get; set; }
        public MEASURING_DATA DeepCopy()
        {
            MEASURING_DATA other = new MEASURING_DATA();    //           
            other.MDA_MODE_ID = ((MEASURING_DATA)this).MDA_MODE_ID;
            other.MDA_F = ((MEASURING_DATA)this).MDA_F;
            other.MDA_F_UNIT_ID = ((MEASURING_DATA)this).MDA_F_UNIT_ID;
            other.MDA_I = ((MEASURING_DATA)this).MDA_I;
            other.MDA_ECN_VALUE_IZM = ((MEASURING_DATA)this).MDA_ECN_VALUE_IZM;
            other.MDA_EN_VALUE_IZM = ((MEASURING_DATA)this).MDA_EN_VALUE_IZM;
            other.MDA_U0CN_VALUE_IZM = ((MEASURING_DATA)this).MDA_U0CN_VALUE_IZM;
            other.MDA_U0N_VALUE_IZM = ((MEASURING_DATA)this).MDA_U0N_VALUE_IZM;
            other.MDA_UFCN_VALUE_IZM = ((MEASURING_DATA)this).MDA_UFCN_VALUE_IZM;
            other.MDA_UFN_VALUE_IZM = ((MEASURING_DATA)this).MDA_UFN_VALUE_IZM;
            other.MDA_ES_VALUE_IZM = ((MEASURING_DATA)this).MDA_ES_VALUE_IZM;
            other.MDA_ECN_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_ECN_VALUE_IZM_DB;
            other.MDA_EN_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_EN_VALUE_IZM_DB;
            other.MDA_U0CN_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_U0CN_VALUE_IZM_DB;
            other.MDA_U0N_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_U0N_VALUE_IZM_DB;
            other.MDA_UFCN_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_UFCN_VALUE_IZM_DB;
            other.MDA_UFN_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_UFN_VALUE_IZM_DB;
            other.MDA_ES_VALUE_IZM_DB = ((MEASURING_DATA)this).MDA_ES_VALUE_IZM_DB;
            other.MDA_ECN_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_ECN_VALUE_IZM_MKV;
            other.MDA_EN_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_EN_VALUE_IZM_MKV;
            other.MDA_U0CN_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_U0CN_VALUE_IZM_MKV;
            other.MDA_U0N_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_U0N_VALUE_IZM_MKV;
            other.MDA_UFCN_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_UFCN_VALUE_IZM_MKV;
            other.MDA_UFN_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_UFN_VALUE_IZM_MKV;
            other.MDA_ES_VALUE_IZM_MKV = ((MEASURING_DATA)this).MDA_ES_VALUE_IZM_MKV;
            other.MDA_EGS_DB = ((MEASURING_DATA)this).MDA_EGS_DB;
            other.MDA_EGS_MKV = ((MEASURING_DATA)this).MDA_EGS_MKV;
            other.MDA_E = ((MEASURING_DATA)this).MDA_E;
            other.MDA_UF = ((MEASURING_DATA)this).MDA_UF;
            other.MDA_U0 = ((MEASURING_DATA)this).MDA_U0;
            other.MDA_EGS = ((MEASURING_DATA)this).MDA_EGS;
            other.MDA_KP = ((MEASURING_DATA)this).MDA_KP;
            other.MDA_KPS = ((MEASURING_DATA)this).MDA_KPS;
            other.MDA_RBW = ((MEASURING_DATA)this).MDA_RBW;
            other.MDA_RBW_UNIT_ID = ((MEASURING_DATA)this).MDA_RBW_UNIT_ID;
            other.MDA_TYPE = ((MEASURING_DATA)this).MDA_TYPE;
            other.MDA_KA = ((MEASURING_DATA)this).MDA_KA;
            other.MDA_KF = ((MEASURING_DATA)this).MDA_KF;
            other.MDA_KF = ((MEASURING_DATA)this).MDA_KF;
            other.MDA_K0 = ((MEASURING_DATA)this).MDA_K0;
            other.MDA_F_BEGIN = ((MEASURING_DATA)this).MDA_F_BEGIN;
            other.MDA_F_END = ((MEASURING_DATA)this).MDA_F_END;
            other.MDA_ECN_BEGIN = ((MEASURING_DATA)this).MDA_ECN_BEGIN;
            other.MDA_EN_BEGIN = ((MEASURING_DATA)this).MDA_EN_BEGIN;
            other.MDA_ECN_END = ((MEASURING_DATA)this).MDA_ECN_END;
            other.MDA_EN_END = ((MEASURING_DATA)this).MDA_EN_END;
            other.MDA_ANGLE = ((MEASURING_DATA)this).MDA_ANGLE;

            return other;
        }


        public virtual MODE MODE { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual UNIT UNIT1 { get; set; }
    }
}
