//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURING_DEVICE_TYPE
    {
        public MEASURING_DEVICE_TYPE()
        {
            this.MEASURING_DEVICE = new HashSet<MEASURING_DEVICE>();
        }
    
        public int MDT_ID { get; set; }
        public string MDT_NAME { get; set; }
        public string MDT_NOTE { get; set; }
    
        public virtual ICollection<MEASURING_DEVICE> MEASURING_DEVICE { get; set; }
    }
}
