//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODE_TYPE
    {
        public MODE_TYPE()
        {
            this.MODE = new HashSet<MODE>();
        }
    
        public int MT_ID { get; set; }
        public string MT_NAME { get; set; }
        public string MT_NOTE { get; set; }
        public Nullable<double> MT_KN { get; set; }
        public string MT_CK { get; set; }
        public Nullable<double> MT_N { get; set; }
        public Nullable<double> MT_M { get; set; }
        public bool MT_ISVISILABLE { get; set; }
        public double MT_F_DEFAULT { get; set; }
    
        public virtual MODE_TYPE MODE_TYPE1 { get; set; }
        public virtual MODE_TYPE MODE_TYPE2 { get; set; }
        public virtual ICollection<MODE> MODE { get; set; }
    }
}
