//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.ANALYSIS = new HashSet<ANALYSIS>();
        }
    
        public int ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_ABBREV { get; set; }
        public string ORG_ADDRES { get; set; }
        public string ORG_NOTE { get; set; }
    
        public virtual ICollection<ANALYSIS> ANALYSIS { get; set; }
    }
}
