//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.ANALYSIS = new HashSet<ANALYSIS>();
            this.ANALYSIS1 = new HashSet<ANALYSIS>();
            this.ANTENNA = new HashSet<ANTENNA>();
            this.ANTENNA1 = new HashSet<ANTENNA>();
            this.FIDER = new HashSet<FIDER>();
            this.FIDER1 = new HashSet<FIDER>();
        }
    
        public int PERSON_ID { get; set; }
        public string PERSON_FIO { get; set; }
        public string PERSON_NOTE { get; set; }
    
        public virtual ICollection<ANALYSIS> ANALYSIS { get; set; }
        public virtual ICollection<ANALYSIS> ANALYSIS1 { get; set; }
        public virtual ICollection<ANTENNA> ANTENNA { get; set; }
        public virtual ICollection<ANTENNA> ANTENNA1 { get; set; }
        public virtual ICollection<FIDER> FIDER { get; set; }
        public virtual ICollection<FIDER> FIDER1 { get; set; }
    }
}
